#!/usr/bin/env node
// Reads the wasm-pack output, base64-encodes the .wasm binary, and writes
// it as a TypeScript source constant. This is what lets consumers of the
// published package `import` this library with zero bundler
// configuration for `.wasm` files — the bytes just live in the JS bundle.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const wasmPath = join(root, "pkg", "useless_buttons_core_bg.wasm");
const outPath = join(root, "src-ts", "wasm-inline.generated.ts");

let bytes;
try {
  bytes = readFileSync(wasmPath);
} catch (err) {
  console.error(`inline-wasm: could not read ${wasmPath}`);
  console.error(`inline-wasm: did "npm run build:wasm" run first?`);
  throw err;
}

const base64 = bytes.toString("base64");

const content =
  `// AUTO-GENERATED by scripts/inline-wasm.mjs — do not edit by hand.\n` +
  `// Regenerate with \`npm run build:wasm && npm run build:glue\`.\n` +
  `export const WASM_BASE64: string = ${JSON.stringify(base64)};\n`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content, "utf8");

const kib = (n) => (n / 1024).toFixed(1);
console.log(
  `inline-wasm: ${kib(bytes.length)}KiB wasm -> ${kib(base64.length)}KiB base64 -> ${outPath}`,
);
